# Generated by Django 5.1.6 on 2025-02-26 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cars',
            new_name='car',
        ),
    ]
